services:
  - type: web
    name: vehicle-tracking-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ML_SERVICE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false